name: syntax-test

on: push

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: Install cpplint
        run: sudo apt-get update && sudo apt-get install -y cpplint
      - name: Install Bazel
        run: |
          sudo apt install apt-transport-https curl gnupg -y
          curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
          sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
          sudo apt update && sudo apt install bazel
          sudo apt update && sudo apt full-upgrade

      - name: run cpplint
        run: cpplint --filter=-legal/copyright ./implementation/hash_map/src/hash_map.hpp

      - name: run all the tests
        run: |
          cd implementation
          bazel test --test_output=all  --cxxopt=-std=c++14 //...:all
